; HARDWARE CONSTANTS FILE
KEY_NULL            equ 0,        ; Key: NULL, used for no key pressed
KEY_APOSTROPHE      equ 39,       ; Key: '
KEY_COMMA           equ 44,       ; Key: ,
KEY_MINUS           equ 45,       ; Key: -
KEY_PERIOD          equ 46,       ; Key: .
KEY_SLASH           equ 47,       ; Key: /
KEY_ZERO            equ 48,       ; Key: 0
KEY_ONE             equ 49,       ; Key: 1
KEY_TWO             equ 50,       ; Key: 2
KEY_THREE           equ 51,       ; Key: 3
KEY_FOUR            equ 52,       ; Key: 4
KEY_FIVE            equ 53,       ; Key: 5
KEY_SIX             equ 54,       ; Key: 6
KEY_SEVEN           equ 55,       ; Key: 7
KEY_EIGHT           equ 56,       ; Key: 8
KEY_NINE            equ 57,       ; Key: 9
KEY_SEMICOLON       equ 59,       ; Key: ;
KEY_EQUAL           equ 61,       ; Key: equ
KEY_A               equ 65,       ; Key: A | a
KEY_B               equ 66,       ; Key: B | b
KEY_C               equ 67,       ; Key: C | c
KEY_D               equ 68,       ; Key: D | d
KEY_E               equ 69,       ; Key: E | e
KEY_F               equ 70,       ; Key: F | f
KEY_G               equ 71,       ; Key: G | g
KEY_H               equ 72,       ; Key: H | h
KEY_I               equ 73,       ; Key: I | i
KEY_J               equ 74,       ; Key: J | j
KEY_K               equ 75,       ; Key: K | k
KEY_L               equ 76,       ; Key: L | l
KEY_M               equ 77,       ; Key: M | m
KEY_N               equ 78,       ; Key: N | n
KEY_O               equ 79,       ; Key: O | o
KEY_P               equ 80,       ; Key: P | p
KEY_Q               equ 81,       ; Key: Q | q
KEY_R               equ 82,       ; Key: R | r
KEY_S               equ 83,       ; Key: S | s
KEY_T               equ 84,       ; Key: T | t
KEY_U               equ 85,       ; Key: U | u
KEY_V               equ 86,       ; Key: V | v
KEY_W               equ 87,       ; Key: W | w
KEY_X               equ 88,       ; Key: X | x
KEY_Y               equ 89,       ; Key: Y | y
KEY_Z               equ 90,       ; Key: Z | z
KEY_LEFT_BRACKET    equ 91,       ; Key: [
KEY_BACKSLASH       equ 92,       ; Key: '\'
KEY_RIGHT_BRACKET   equ 93,       ; Key: ]
KEY_GRAVE           equ 96,       ; Key: `
; Function keys
KEY_SPACE           equ 32,       ; Key: Space
KEY_ESCAPE          equ 256,      ; Key: Esc
KEY_ENTER           equ 257,      ; Key: Enter
KEY_TAB             equ 258,      ; Key: Tab
KEY_BACKSPACE       equ 259,      ; Key: Backspace
KEY_INSERT          equ 260,      ; Key: Ins
KEY_DELETE          equ 261,      ; Key: Del
KEY_RIGHT           equ 262,      ; Key: Cursor right
KEY_LEFT            equ 263,      ; Key: Cursor left
KEY_DOWN            equ 264,      ; Key: Cursor down
KEY_UP              equ 265,      ; Key: Cursor up
KEY_PAGE_UP         equ 266,      ; Key: Page up
KEY_PAGE_DOWN       equ 267,      ; Key: Page down
KEY_HOME            equ 268,      ; Key: Home
KEY_END             equ 269,      ; Key: End
KEY_CAPS_LOCK       equ 280,      ; Key: Caps lock
KEY_SCROLL_LOCK     equ 281,      ; Key: Scroll down
KEY_NUM_LOCK        equ 282,      ; Key: Num lock
KEY_PRINT_SCREEN    equ 283,      ; Key: Print screen
KEY_PAUSE           equ 284,      ; Key: Pause
KEY_F1              equ 290,      ; Key: F1
KEY_F2              equ 291,      ; Key: F2
KEY_F3              equ 292,      ; Key: F3
KEY_F4              equ 293,      ; Key: F4
KEY_F5              equ 294,      ; Key: F5
KEY_F6              equ 295,      ; Key: F6
KEY_F7              equ 296,      ; Key: F7
KEY_F8              equ 297,      ; Key: F8
KEY_F9              equ 298,      ; Key: F9
KEY_F10             equ 299,      ; Key: F10
KEY_F11             equ 300,      ; Key: F11
KEY_F12             equ 301,      ; Key: F12
KEY_LEFT_SHIFT      equ 340,      ; Key: Shift left
KEY_LEFT_CONTROL    equ 341,      ; Key: Control left
KEY_LEFT_ALT        equ 342,      ; Key: Alt left
KEY_LEFT_SUPER      equ 343,      ; Key: Super left
KEY_RIGHT_SHIFT     equ 344,      ; Key: Shift right
KEY_RIGHT_CONTROL   equ 345,      ; Key: Control right
KEY_RIGHT_ALT       equ 346,      ; Key: Alt right
KEY_RIGHT_SUPER     equ 347,      ; Key: Super right
KEY_KB_MENU         equ 348,      ; Key: KB menu
; Keypad keys
KEY_KP_0            equ 320,      ; Key: Keypad 0
KEY_KP_1            equ 321,      ; Key: Keypad 1
KEY_KP_2            equ 322,      ; Key: Keypad 2
KEY_KP_3            equ 323,      ; Key: Keypad 3
KEY_KP_4            equ 324,      ; Key: Keypad 4
KEY_KP_5            equ 325,      ; Key: Keypad 5
KEY_KP_6            equ 326,      ; Key: Keypad 6
KEY_KP_7            equ 327,      ; Key: Keypad 7
KEY_KP_8            equ 328,      ; Key: Keypad 8
KEY_KP_9            equ 329,      ; Key: Keypad 9
KEY_KP_DECIMAL      equ 330,      ; Key: Keypad .
KEY_KP_DIVIDE       equ 331,      ; Key: Keypad /
KEY_KP_MULTIPLY     equ 332,      ; Key: Keypad *
KEY_KP_SUBTRACT     equ 333,      ; Key: Keypad -
KEY_KP_PLUS         equ 334,      ; Key: Keypad +
KEY_KP_ENTER        equ 335,      ; Key: Keypad Enter
KEY_KP_EQUAL        equ 336,      ; Key: Keypad equ